"""Add 52 week high and low to Stock model

Revision ID: 5774b73efdfe
Revises: c8009eeb0287
Create Date: 2025-01-27 11:07:13.835238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5774b73efdfe'
down_revision: Union[str, None] = 'c8009eeb0287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('week_52_high', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('week_52_low', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'week_52_low')
    op.drop_column('stocks', 'week_52_high')
    # ### end Alembic commands ###
