"""Add market_cap and pe_ratio to Stock model

Revision ID: c8009eeb0287
Revises: e9df4a7334ba
Create Date: 2025-01-27 10:37:25.726631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8009eeb0287'
down_revision: Union[str, None] = 'e9df4a7334ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('market_cap', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('pe_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'pe_ratio')
    op.drop_column('stocks', 'market_cap')
    # ### end Alembic commands ###
